### ISSUE TITLE
How much does the pool makes if a block is found? after paying all miners still %1 from the block?

### ISSUE THREAD

**Issue by Coinizy1** [CryptoManiac/open-ethereum-pool-pps#10]
Hi
I have a small question this is a PPS script so I should have balance in eth address no problem.  Now how this pool will earn?
Thanks

**Comment by CryptoManiac** [comment]
Hi. You will receive full block reward every time when the block is found. 

As the result, you will get a difference from sum of block rewards and the sum of payments which are being made to users. Sometimes it can be negative, sometimes positive. But in average it will tend to be equal with PPS fee.

P.S. BTW, you shouldn't forget that there are transaction  fees which are also accounted as a part of block reward. So the real difference will be slightly higher than PPS fee.
