### ISSUE TITLE
Hi. Help Update

### ISSUE THREAD

**Issue by xenhim** [CryptoManiac/open-ethereum-pool-pps#11]
I see your website pool is running. Found a very good block. Now the blocks are too hard to Found. Can you share what you have updated and what is the best parity command? . Does the code pool need an update? . I make a site pool for the asian area

**Comment by xenhim** [comment]
pool pps. Use parity with how optimal settings are. help me . Can anyone tell me ?

**Comment by CryptoManiac** [comment]
Block generation process is like a dice game. You can't tweak it to perform better, everything depends on your luck. Sometimes there are lucky rounds, sometimes there are no such rounds.
