### ISSUE TITLE
Payout not work

### ISSUE THREAD

**Issue by minersbad** [CryptoManiac/open-ethereum-pool-pps#14]
Hi to all,

i have one problem 
i have setup payout to 0.05ETH, also file payout.json separated to config.
but i have over 0.05 and not pay.
 Pending Balance: 0.05293288
Credited coins awaiting payout.
 Total Paid: 0.00000000
why ?

**Comment by minersbad** [comment]
2018/02/24 20:34:03 Loading config: /home/salvo/open-ethereum-pool/build/bin/payout.json
2018/02/24 20:34:03 Running with 2 threads
2018/02/24 20:34:03 Backend check reply: PONG
2018/02/24 20:34:03 Starting payouts
2018/02/24 20:34:03 Set payouts interval to 1m0s
2018/02/24 20:34:03 No payees that have reached payout threshold

**Comment by CryptoManiac** [comment]
Hi. May you publish your payout configuration file?

**Comment by CryptoManiac** [comment]
BTW, 1 minutes is too small for production purposes... Having short payout interval increases operator's variance. With long interval there is a possibility to find more blocks between payouts so it's more safe. There would be a less probability that your wallet will be emptied because of payments to some nicehash user without payments to normal miners.

**Comment by minersbad** [comment]
the payout interval is only for test.
here my payout config. still now not payed

{
        "threads": 2,
        "coin": "eth",
        "name": "main",

        "proxy": {
                "enabled": false,
                "listen": "0.0.0.0:8888",
                "limitHeadersSize": 1024,
                "limitBodySize": 256,
                "behindReverseProxy": false,
                "blockRefreshInterval": "120ms",
                "stateUpdateInterval": "3s",
                "difficulty": 2000000000,
                "hashrateExpiration": "3h",

                "healthCheck": true,
                "maxFails": 100,

                "stratum": {
                        "enabled": false,
                        "listen": "0.0.0.0:8008",
                        "timeout": "120s",
                        "maxConn": 8192
                },

                "policy": {
                        "workers": 8,
                        "resetInterval": "60m",
                        "refreshInterval": "1m",

                        "banning": {
                                "enabled": false,
                                "ipset": "blacklist",
                                "timeout": 1800,
                                "invalidPercent": 30,
                                "checkThreshold": 30,
                                "malformedLimit": 5
                        },
                        "limits": {
                                "enabled": false,
                                "limit": 30,
                                "grace": "5m",
                                "limitJump": 10
                        }
                }
        },

        "api": {
                "enabled": false,
                "purgeOnly": false,
                "purgeInterval": "10m",
                "listen": "0.0.0.0:8080",
                "statsCollectInterval": "5s",
                "hashrateWindow": "30m",
                "hashrateLargeWindow": "3h",
                "luckWindow": [64, 128, 256],
                "payments": 30,
                "blocks": 50
     
   },

        "upstreamCheckInterval": "5s",
        "upstream": [
                {
                        "name": "main",
                        "url": "http://127.0.0.1:8545",
                        "timeout": "10s"
                },
                {
                        "name": "backup",
                        "url": "http://127.0.0.2:8545",
                        "timeout": "10s"
                }
        ],

        "redis": {
                "endpoint": "127.0.0.1:6379",
                "poolSize": 10,
                "database": 0,
                "password": ""
        },

        "unlocker": {
                "enabled": false,
                "poolFee": 1.0,
                "poolFeeAddress": "",
                "depth": 120,
                "immatureDepth": 20,
                "keepTxFees": false,
                "interval": "10m",
                "daemon": "http://127.0.0.1:8545",
                "timeout": "10s"
        },

        "payouts": {
                "enabled": true,
                "requirePeers": 1,
                "interval": "1m",
                "daemon": "http://127.0.0.1:8545",
                "timeout": "10s",
                "address": "0xe7345230635ddfa968639c0198bee7e137b2af5d",
                "gas": "21000",
                "gasPrice": "50000000000",
                "autoGas": true,
                "threshold": 500000000,
                "bgsave": false
        },

        "newrelicEnabled": false,
        "newrelicName": "MyEtherProxy",
        "newrelicKey": "SECRET_KEY",
        "newrelicVerbose": false
}

**Comment by minersbad** [comment]
give me your $kype id please

**Comment by CryptoManiac** [comment]
```
            "threshold": 500000000,
```

This means that your threshold is 0.5 Ether, not 0.05.

**Comment by minersbad** [comment]
i need addo 0 ? because i have tryed with one 0 more and remove one 0 same problem

**Comment by minersbad** [comment]
i need setup 0.05

**Comment by CryptoManiac** [comment]
https://etherconverter.online/

0.05 ether = 50000000 GWei

**Comment by minersbad** [comment]
i have do it but same problem

**Comment by CryptoManiac** [comment]
https://etherscan.io/address/0xe7345230635ddfa968639c0198bee7e137b2af5d

Is this an actual address?

**Comment by minersbad** [comment]
is not address of miner. 
check here
http://europe.instapool.eu/#/account/0xb85daea5db18f5f5c0bc0d97cdc2fa072d40c6b7

**Comment by CryptoManiac** [comment]
I mean that pool is not able to get coins out of thin air. If this is an actual coinbase address then it's quite expectable behaviour, because there is no money to conduct payments.

**Comment by minersbad** [comment]
is the personal address from geth when i have installed it. How i know if work good or not?

**Comment by CryptoManiac** [comment]
First, ensure that pool is able to make payments. Your geth should have access to private key of this address and it should be unlocked for infinite amount of time. This could be done by passing --unlock command line option to geth.

After that you need to fund this address with some coins and see what will happen. If everything is fine then pool wil perform payment and write its information into logs.

**Comment by minersbad** [comment]
now address have 0.06 ETH 
https://etherscan.io/address/0xe7345230635ddfa968639c0198bee7e137b2af5d

now send payment ?

**Comment by minersbad** [comment]
which is the complete geth string that i need to use for supervisor conf?

**Comment by CryptoManiac** [comment]
I suppose it should be something like that:

```
geth --rpc --etherbase 0xe7345230635ddfa968639c0198bee7e137b2af5d --unlock 0xe7345230635ddfa968639c0198bee7e137b2af5d --password /path/to/text/file/with/account/password.txt
```

But I'd say it's better to use parity, it's faster and there is an example configuration file:

https://github.com/CryptoManiac/open-ethereum-pool-pps/blob/master/docs/config.toml

**Comment by minersbad** [comment]
instead 
--password /path/to/text/file/with/account/password.txt 
can i use --password "password" ?

**Comment by CryptoManiac** [comment]
No, it's not supported by any wallet for obvious reasons.

**Comment by minersbad** [comment]
i have added path but when i check in geth attach i have this one
 web3.personal
{
  listAccounts: ["0xe7345230635ddfa968639c0198bee7e137b2af5d"],
  listWallets: [{
      accounts: [{...}],
      status: "Locked"

**Comment by CryptoManiac** [comment]
Heh, payments won't work with locked wallet. Try to unlock it from console, using personal.unlockAccount method or through command line option... Maybe there is a typo in your password file or no carriage return at the end of password.

**Comment by minersbad** [comment]
payment unlock. done :)
