### ISSUE TITLE
Unlocking blocks

### ISSUE THREAD

**Issue by nikolayklimov** [CryptoManiac/open-ethereum-pool-pps#16]
I set up your pool on misic coin node to check out the payout system.

before building the pool i changed block rewards in unlocker.go,  and  environment.js
when i tried to set unlocker in config.json on true i received "Block maturity depth can't be < 32, your depth is 0"
 how to fix it?
with all this running, when the block is found it does not go through maturity.
http://54.202.140.221/#/blocks/pending
is there something what i missed to setup?

minor question 1,
where web interface takes rewards amount if not from unlocker.go?
as you can see on the website network data is correct for music coin but the payout estimate and panding balance are calculated wrong
how to fix it?

**Comment by CryptoManiac** [comment]
You don't need unlocker since payment system is independent from rounds. Just disable it to save resources and that will resolve your issue. Blocks will remain as immature forever, but who cares about that...

**Comment by CryptoManiac** [comment]
If you mine some fork then you need to change block reward in GetShareReward function, which is defined in util.go file. Otherwise it will account shares as if they were ethereum shares.

**Comment by nikolayklimov** [comment]
this is interesting, thanks for quick response.
do you mean here?
func GetShareReward(shareDiff, netDiff int64, fee float64) float64 {
	wei := new(big.Rat).SetInt(Ether)
	wei.Mul(wei, new(big.Rat).SetInt64(**3**))

**Comment by CryptoManiac** [comment]
Yes.

**Comment by nikolayklimov** [comment]
after that i tried to compile pool and web interface still the same, trying to play around

**Comment by CryptoManiac** [comment]
This change won't affect the value of already accounted shares.

By the way, you will also need to edit www/app/controllers/account.js and www/app/routes/index.js if you wish to make payment estimations work correctly. Yes, I know that there are too much hard coded values... Eventually this will be put in order.

**Comment by nikolayklimov** [comment]
i dont worry about bankruptcy risks for now i have enough power to mine on my own a few blocks in advance

**Comment by CryptoManiac** [comment]
This change won't affect the value of already accounted shares.

By the way, you will also need to edit www/app/controllers/account.js and www/app/routes/index.js if you wish to make payment estimations work correctly. Yes, I know that there are too much hard coded values... Eventually this will be put in order.

**Comment by nikolayklimov** [comment]
all this make sense, how about payout system, i did not try it yet, is there something hardcoded as well?

**Comment by CryptoManiac** [comment]
As I said before, GetShareReward function contains hard coded value of block reward. WriteShare function calls it with hard coded value of mining fee which is set to 1.5%. I think that's all.

**Comment by nikolayklimov** [comment]
thank you for support

**Comment by nikolayklimov** [comment]
I guess you are Russian, is there a way to contact you outside the git?

**Comment by CryptoManiac** [comment]
I think it's a good idea to mention that fee related settings of the config.json file are absolutely senseless with PPS since its rewarding users directly without using block unlocker. That is why I prefer to disable it.

> is there a way to contact you outside the git?

Unfortunately, I currently don't have enough time for this project and related issues.

**Comment by nikolayklimov** [comment]
related your last message, the question, does the payout module in config.json work properly?

**Comment by CryptoManiac** [comment]
Of course it does. This code is currently serves my pool.

**Comment by nikolayklimov** [comment]
Thanks again

**Comment by muhammad-05** [comment]
Sorry about the wrong branch, but I wanted to know. how to determine the reward for a particular coin?
