### ISSUE TITLE
block not payed (HELP PLEASE)

### ISSUE THREAD

**Issue by minersbad** [CryptoManiac/open-ethereum-pool-pps#17]
Hi i have problem

we have find 3 block but when miner pool address receive funds automatic go in other address
http://gastracker.io/addr/0xe5de50fe61e9f5c2847081214f56f29478a9dee8

can u help me?

**Comment by CryptoManiac** [comment]
To be honest, I didn’t realize what do you mean. Is this your pool’s mining address?

**Comment by CryptoManiac** [comment]
If there are no such miner on your pool, then, please, ensure that your private key is not compromised.

**Comment by CryptoManiac** [comment]
Another recommendation is to avoid using VPS for serving mining pools. Especially provided by cheap hosters. Hosting staff has access to every byte of your RAM, so no encryption would save you from a hand of greedy virtualization admin.

**Comment by minersbad** [comment]
How I setup key rpc?

Il giorno ven 2 mar 2018 alle 23:05 CryptoManiac <notifications@github.com>
ha scritto:

**Comment by minersbad** [comment]
how i can protect rpc? i dont know where setting password

**Comment by CryptoManiac** [comment]
Password is used for private key encryption, not for RPC. Anyway setting password won't help if your key was already compromised. Hacker don't need access to your server if he already exported your key into own wallet.
