### ISSUE TITLE
pool payout

### ISSUE THREAD

**Issue by itsmylife44** [CryptoManiac/open-ethereum-pool-pps#18]
hi, I did the whole configuration, set parity, made unlock the wallet, and all the rest, but on my wallet there is no balance to pay the individual miner.

Where am I wrong?

**Comment by CryptoManiac** [comment]
Hi. Of course there will be no balance becase pool can't create coins from nothing. It needs either to find a block or manual funding. 

If you're starting brand new pool then wallet balance should be filled with some funds which are sufficient for planned daily payment. After pool will start finding blocks you will need to maintain this level of balance manually, by depositing additional or withdrawing excessive funds.

**Comment by CryptoManiac** [comment]
There is also another way - you can continue mining and wait until pool will find enough blocks to pay your miners. But it may be difficult to attract miners with such a policy since most of them are expecting payments made as soon as possible.

**Comment by itsmylife44** [comment]
ok, thanks for the info. Yes, the pool is new but I already have several customers who would undermine the pool. in your opinion, how many hashes are used to solve blocks? I read around but I did not understand much. I would be grateful for your response, and thank you for your work!

**Comment by CryptoManiac** [comment]
Hi. Network difficulty is an average amount of hashes needed to find a block. You can find block earlier or later though.

**Comment by CryptoManiac** [comment]
You may also calculate a probability of negative result, i.e. having no block while performing given amount of work.

```Pn = 1 - P```

**Comment by itsmylife44** [comment]
is it working with etc ?

**Comment by CryptoManiac** [comment]
Yes but you need to adjust block reward values.
