### ISSUE TITLE
Pool cant start .  

### ISSUE THREAD

**Issue by itsmylife44** [CryptoManiac/open-ethereum-pool-pps#19]
#### System information

Geth version: `geth version` or commit hash if `develop`
version Parity/v1.9.0-beta-53ec114-20180125/x86_64-linux-gnu/rustc1.23.0
Redis version: `redis-server --version`
Redis server v=4.0.8
OS & Version: Linux/OSX
Linux
Commit branch and hash: (`master`, `ba60e1c`)
master
#### Expected behaviour
cant start pool 

#### Actual behaviour
Config error: invalid character '"' after object key:value pair

#### Backtrace

````
[backtrace]
````

**Comment by CryptoManiac** [comment]
This looks like a result of syntax error in the configuration file.

**Comment by CryptoManiac** [comment]
Try to ensure that your configuration file is in valid json data format.

P.S. I think that your issue was caused by absence of comma here: https://github.com/CryptoManiac/open-ethereum-pool-pps/commit/8d54b15ddaf8dc25d654f39f603e4c0b4a222cfd
