### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by vtnplus** [CryptoManiac/open-ethereum-pool-pps#2]
Hi friend i have problem, you can help me ?
i have get error form claymore with report "Receied unknow response: {”id” : null, “ ”method” : “minning.notifu”, “param” : “.....”". where i can fix it

**Comment by CryptoManiac** [comment]
It's most likely that you're using incompatible stratum mode.

**Comment by vtnplus** [comment]
ah CryptoManiac. I think PPS dong need unlock block. this is nice solution. i want develop with you. but what is PPS solution in code

**Comment by CryptoManiac** [comment]
What do you mean? There is no rounds in PPS, so you actually don't need unlocker, variance and shares data. Related parts of code can be removed freely, without any significant consequences.

**Comment by vtnplus** [comment]
anh we need add function marketing.
sample  : when member found 1 block we can +0.01 ETH for him blancer.
What do you think about

**Comment by CryptoManiac** [comment]
That would require additional fee, since you're unable to get these 0.01 ethers out of thin air.

**Comment by vtnplus** [comment]
kkk we can deposit :D

**Comment by vtnplus** [comment]
open-ethereum-pool-pps
can support nicehash friend ?

**Comment by vtnplus** [comment]
Your develop PPS can work with ETC, EXP, MUSIC.... ? or only ETH

**Comment by CryptoManiac** [comment]
```Your develop PPS can work with ETC, EXP, MUSIC.... ? or only ETH```

You need to edit GetShareReward function to set a proper block reward.

https://github.com/CryptoManiac/open-ethereum-pool-pps/blob/master/util/util.go#L62

You will also need to reconsider your risks since ETH table was calculated using 5 ETH block reward and becomes incorrect for other values.

I mean this table:

https://onedrive.live.com/edit.aspx?cid=b7696362a12d3f44&page=view&resid=B7696362A12D3F44!19454&parId=B7696362A12D3F44!564&app=Excel

**Comment by CryptoManiac** [comment]
It is also most likely that you will need to set much higher fee for MUSIC and other forks with high block reward.

**Comment by vtnplus** [comment]
yes. sample EXP block reward = 8, wei.Mul(wei, new(big.Rat).SetInt64(8)) but when set unlock = false, where is fee ?

**Comment by CryptoManiac** [comment]
https://github.com/CryptoManiac/open-ethereum-pool-pps/blob/master/storage/redis.go#L234

1.5 means 1.5%.
