### ISSUE TITLE
Do you still work on this project?

### ISSUE THREAD

**Issue by SeekWorld** [CryptoManiac/open-ethereum-pool-pps#23]
Hope to see your return.
The Constantinople Hardfork is approaching

**Comment by CryptoManiac** [comment]
Hi. That shouldn't be hard to implement, just replace base reward value with 2 ETH and it's done.
I think I'll find some time soon.

**Comment by rlinxy** [comment]
line 71 in util.go, just modify number '3' to '2' should work

**Comment by SeekWorld** [comment]
Hi! @CryptoManiac  & @rlinxy   Thank for your code and help. BEST WISH TO YOU!
