### ISSUE TITLE
This is not an issue just 2 small questions please.

### ISSUE THREAD

**Issue by Coinizy1** [CryptoManiac/open-ethereum-pool-pps#3]
Hi, Is this pool similar to Sammy's Open Ethereum Pool but we don't have to wait to find a block to see balance right?
Should i run the geth with --unlock or not?
Thanks

**Comment by CryptoManiac** [comment]
Yes. Of course you will need to run unlocked geth instance to make payments. You will also need some reserve funds for payments. Amount of reserve funds must be sufficient to provide an ability of payment processing during a lond periods of bad luck. 

Here is the probability of bancruptcy depending on PPS fee and the amount of reserves.

https://1drv.ms/x/s!AkQ_LaFiY2m3gZd-X-QjbChOcrTO1g

**Comment by Coinizy1** [comment]
Okay Thankyou so much bro i never had such quick reply i am literally crying now :(
One last question and i am already praying for your whole family.
That address i get from "geth account new" shall be entered in poolfeeaddress and unlocker in config.json and it should have some balance to make payments right?
Will it show miner's balance on each accepted share right?
Prays are not a bribe it is coming from my heart, Sir.
Thank YOU.

**Comment by Coinizy1** [comment]
and why i have to clone the Sammy's version you added in readme file. I dont want PROP i want PPS so i have clone this?
Thanks

**Comment by CryptoManiac** [comment]
I think that I'll eventually find some time to adjust the configuration code in order to make it more PPS-friendly.

**Comment by CryptoManiac** [comment]
By the way, this project can be seen action here:

https://etherdig.net/

**Comment by Coinizy1** [comment]
Currently i have to clone this git and once it is done i have to add some balance in my Geth account new and it will show a balance of a miner on each accepted hash. i am sorry iam very noob just learning things.

**Comment by CryptoManiac** [comment]
```and it will show a balance of a miner on each accepted hash```

Yes, that's an exact idea.

**Comment by Coinizy1** [comment]
Thank YOU can i found you one gitter?

**Comment by Coinizy1** [comment]
and https://etherdig.net/ doesnt update balance on a miner on last accepted hashrate why is it PROP?

**Comment by Coinizy1** [comment]
oh it does sorry.

**Comment by Coinizy1** [comment]
World's best person to ask help.
Thank YOU.
