### ISSUE TITLE
domain.com also shows and works i only want to mine and show frontend on subdomain

### ISSUE THREAD

**Issue by Coinizy1** [CryptoManiac/open-ethereum-pool-pps#5]
Hi, First of all sir, Thank you so much for this PPS :)
This is not an issue, I just want a hint.  I have entered my subdomain in config/enviroment.js
like
apiurl: subdumain.domain.com etc
and this is my nginx.conf file
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

   sendfile on;
   tcp_nopush on;
   tcp_nodelay on;
   keepalive_timeout 65;
   types_hash_max_size 2048;
   # server_tokens off;

   # server_names_hash_bucket_size 64;
   # server_name_in_redirect off;

   include /etc/nginx/mime.types;
   default_type application/octet-stream;

   ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
   #ssl_prefer_server_ciphers on;

   access_log /var/log/nginx/access.log;
   error_log /var/log/nginx/error.log;

   gzip on;
   gzip_disable "msie6";

   upstream api {
 server 127.0.0.1:8080;
   }

   server {
   listen 0.0.0.0:80;
   root /open-ethereum-pool-pps/www/dist;
   index index.html index.htm;

   server_name localhost;

        location /api {
                proxy_pass http://api;
        }

   location / {
      try_files $uri $uri/ /index.html;
   }

   }
}
I Only want to show the frontend and mining work from subdomain not main domain.  I want to install WordPress on main domain.
can you give me small hint what to do.
thanks

**Comment by CryptoManiac** [comment]
Hello. I don't think that it's a good idea to have wordpress, geth and mining pool running on the same machine. It would be better to have separate hardware or vurtual machines for that purpose.

**Comment by Coinizy1** [comment]
Thank YOU,
If i setup 2 instance then shall i add "A host" for the www to the other WordPress Server?
what will be the setup please explain in simple words
thanks

**Comment by Coinizy1** [comment]
Even if i run a 24 gb ram server it isn't good?
Thanks

**Comment by CryptoManiac** [comment]
It's not good in terms of security.

**Comment by Coinizy1** [comment]
Still can you give me some tip how to do it please :( i don't need security. please
