### ISSUE TITLE
Can i use apache? Is yes then only www/dist will be served right?

### ISSUE THREAD

**Issue by Coinizy1** [CryptoManiac/open-ethereum-pool-pps#6]
Hi i want to use apache to serve front end.  Is it possible?
Thanks

**Comment by Coinizy1** [comment]
@CryptoManiac Sir, 
please answer if you are available for a minute.
Thanks

**Comment by CryptoManiac** [comment]
Yes, you can, though it's recommended to use some lightweight server like nginx or lighttpd.
