### ISSUE TITLE
Can i use this for LTC pool too?

### ISSUE THREAD

**Issue by Coinizy1** [CryptoManiac/open-ethereum-pool-pps#8]
Hi, I want to setup the Litecoin pool so i will change the config.json to "ltc" will it work?
thanks

**Comment by CryptoManiac** [comment]
Hi. Nope, it won't work because LTC or BTC are totally different. Their APIs are absolutely incompatible with ETH.

You would probably be able to use node-stratum-pool though, but there is a need to merge support for scrypt PoW first.
