### ISSUE TITLE
Very small Question! Please

### ISSUE THREAD

**Issue by Coinizy1** [CryptoManiac/open-ethereum-pool-pps#9]
I want to see my total profit at 1.5% from all miners (total earnings from all miners).
What i want to do is, i want to see how much fee (earnings) my pool is making with each miner. something like
All.model.stats.balance  x 1.5 (fee) / 100 = Pool profit.    ( This is just an example i want to know how can i get this done just guide me to direction thanks)
Thanks

**Comment by CryptoManiac** [comment]
I'd say that your only actual earnings are transaction fees. PPS fee can't be considered as the way to make profits, it works as a kind of compensation for variance related risks.
